// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run over the session-mode pooler (supports DDL); the app's
    // own PrismaClient uses DATABASE_URL (transaction-mode pooler) instead.
    url: process.env["DIRECT_URL"],
  },
});
